### ISSUE TITLE
Windows WebPush Token?

### ISSUE THREAD

**Issue by CR4567** [notifo-io/notifo#139]
I'm wondering about the second entry here:
![Bildschirmfoto 2022-11-08 um 12 45 01](https://user-images.githubusercontent.com/10132368/200556431-33f97997-e374-469d-9854-acd45e152445.png)
Why is there a Win Token? Feature or Issue?

I tried to delete this token and figured out that the garbage button is also not working.

**Comment by SebastianStehle** [comment]
I think the delete button is already fixed.

**Comment by CR4567** [comment]
Just updated to the latest version but still have this issue
